lil-lab/recnet

.github/pull_request_template.md
package.json
pnpm-lock.yaml
src/app/feeds/page.tsx
src/app/user/[username]/page.tsx
src/components/RecCard.tsx
src/server/rec.ts
src/types/rec.ts

Change how we present recs.
- #118 
- #135 
- #45 
Besides modifying the UI layout of RecCard, I also modified the interface of the RecCard component to handle the case that multiple users recommend the same paper.
However, currently, there's no good way to decide whether two rec are the same. I used `lowercase(title)` and trim empty characters as the "unique key" of a paper. And if two recs have the same unique key, we see those papers as the same.
It's not a robust enough way to get the unique key of a paper. What if A and B recommended a paper and A or B's rec has a typo in the title? I don't think using the "URL" to the paper as the unique key is a good solution either. What if two URLs are different but actually point to the same paper?
In the future, we need to design a way to …

Redesign Rec Card

---

apps/recnet/src/app/all-users/page.tsx
apps/recnet/src/app/search/page.tsx
apps/recnet/src/components/UserCard.tsx
apps/recnet/src/server/rec.ts
apps/recnet/src/utils/shuffle.ts
package.json
pnpm-lock.yaml

#140
shuffle users in search page and all-users page
- #140

fix: shuffle users in search page and all-users page

---

apps/recnet-api/src/main.ts
package.json
pnpm-lock.yaml

Create swagger for recnet-api
N/A
After this pr is merged, you can see a swagger API doc page through `https://dev-api.recnet.io/api`
N/A

Create swagger api doc

---

apps/recnet-api/package.json

To maintain recnet-api's own deploy version, I created a separate package.json under the apps/recnet-api.
N/A
N/A
N/A

[recnet-api] Add package.json

---

.github/workflows/ci.yml
.github/workflows/recnet-api-ci.yml
apps/recnet-api/package.json

Create version bump CI for recnet-api
N/A
The github action will be trigger when `apps/recnet-api/package.json` is modified.
N/A

[recnet-api] Create CI

---

apps/recnet-api/package.json
apps/recnet-api/src/database/repository/user.repository.ts

Testing link: https://dev-api.recnet.io/api
Add partial search
https://github.com/lil-lab/recnet/pull/193
N/A
N/A

[recnet-api][v1.1.1] Deploy partial search

---

apps/recnet-api/src/modules/email/email.const.ts
apps/recnet-api/src/modules/email/email.controller.ts

Change Cron Schedule to every Tuesday
https://github.com/lil-lab/recnet/pull/204
https://github.com/lil-lab/recnet/issues/171
N/A

[recnet-api] Change Cron Schedule to every Tuesday

---

.gitignore
apps/recnet-docs/src/pages/_meta.json
apps/recnet-docs/src/pages/scripts.mdx
scripts/vercel-build-ignore.sh

Add script to decide whether ignoring build or not that runs on Vercel. 
Usage:
```sh
sh scripts/vercel-build-ignore.sh <app>
```

chore: add build ignore script for vercel

---

apps/recnet-api/src/database/repository/user.repository.ts
apps/recnet-api/src/modules/user/dto/query.users.dto.ts

Add affiliation to user search
- https://github.com/lil-lab/recnet/issues/197
N/A

[recnet-api] Add affiliation and case insensitive to user search

---

apps/recnet-api/package.json
apps/recnet-api/src/modules/email/email.const.ts

Hotfix resend weekly digest cron
N/A
Will change the cron schedule back to `0 0 0 * * 3` after resending.

[recnet-api][v1.2.3] Hotfix resend weekly digest cron

---

apps/recnet-api/package.json
apps/recnet-api/src/modules/email/email.const.ts
apps/recnet-api/src/modules/email/email.service.ts
apps/recnet-api/src/modules/email/transporters/email.transporters.ts

We faced the error `Temporary System Problem. Try again later (10).` Thus, we try to do the workaround solution, which is to sleep 1 sec between each sending action.
Ref: https://stackoverflow.com/questions/39097834/gmail-smtp-error-temporary-block
N/A

[recnet-api][v1.2.4] Hotfix Gmail SMTP rate limit and resend to failed users

---

apps/recnet-api/src/modules/email/email.service.ts

Skip email if there is no recs
- https://github.com/lil-lab/recnet/issues/202

[recnet-api] Skip email if there is no recs

---

apps/recnet/src/app/layout.tsx

Remove loading local font

---

apps/recnet-api/src/database/repository/announcement.repository.ts
apps/recnet-api/src/modules/announcement/announcement.controller.ts

- Fix the announcement controller typo
- Add orderBy createdAt desc in findAnnouncements
N/A
N/A

fix: patch announcement typo

---

apps/recnet/CHANGELOG.md
apps/recnet/package.json
apps/recnet/src/app/about/page.tsx
apps/recnet/src/app/help/page.tsx

Update the intro video at `help` page and `about` page.
- #251

[recnet-web][v1.9.2] chore: update video

---

apps/recnet-api/package.json
apps/recnet-api/src/database/repository/rec.repository.ts
apps/recnet-api/src/database/repository/rec.repository.type.ts
apps/recnet-api/src/modules/rec/rec.controller.ts
apps/recnet-api/src/modules/rec/rec.service.ts

Fix announcements API bugs
Dev API doc: [https://dev-api.recnet.io/api](https://dev-api.recnet.io/api)
- https://github.com/lil-lab/recnet/issues/249
PRs: 
- https://github.com/lil-lab/recnet/pull/250

[recnet-api][v1.3.3] Fix bug of upcoming rec appearing on profile

---

apps/recnet/CHANGELOG.md
apps/recnet/package.json
apps/recnet/src/app/page.tsx
apps/recnet/src/components/AnnouncementCard.tsx

Add invite code req form to announcement
- #257

[recnet-web][v1.9.3] chore: add invite code req form

---

apps/recnet/CHANGELOG.md
apps/recnet/package.json
apps/recnet/src/app/about/page.tsx
apps/recnet/src/app/page.tsx

Update about page and add an intro video at landing page
- #251 
- #265

[recnet-web][v1.10.0] Update about page

---

.vscode/settings.json
apps/recnet-api/prisma/migrations/20240912022639_add_digital_library_table/down.sql
apps/recnet-api/prisma/migrations/20240912022639_add_digital_library_table/migration.sql
apps/recnet-api/prisma/schema.prisma

Add digital library table in database
- https://github.com/lil-lab/recnet/issues/254
- [Design Doc](https://www.notion.so/Digital-Libraries-Integration-arXiv-26e1673576a84541bb4d789fea2ff518)

[recnet-api] Add digital library table in database

---

.github/workflows/release-action.yml
.prettierignore
libs/recnet-release-action/.eslintrc.json
libs/recnet-release-action/README.md
libs/recnet-release-action/action.yml
libs/recnet-release-action/out/index.js
libs/recnet-release-action/package.json
libs/recnet-release-action/project.json
libs/recnet-release-action/src/index.ts
libs/recnet-release-action/src/lib/env.ts
libs/recnet-release-action/src/lib/github.spec.ts
libs/recnet-release-action/src/lib/github.ts
libs/recnet-release-action/src/lib/main.ts
libs/recnet-release-action/tsconfig.json
libs/recnet-release-action/tsconfig.lib.json
libs/recnet-release-action/tsconfig.spec.json
libs/recnet-release-action/vite.config.ts
lint-staged.config.js
package.json
pnpm-lock.yaml

Automate "Release PR" creation from `dev` to `master` by GitHub Action and GitHub API.
[Learn more about the implementation details in design docs](https://www.notion.so/Unify-workflow-Prod-auto-release-pipeline-10a51bd6607c8043a4b8ff79e97f575d?pvs=4)
N/A
Unfortunately, this can’t be test easily. Except the unit tests I wrote, the only way to test the action is to manually dispatch this action in the “action” tab in GitHub. However, this only works when `dev` branch is ahead of `master` (currently, they are in-sync).

Auto release bot: recnet-release-action

---

apps/recnet-api/src/database/repository/rec.repository.ts

1. Prioritize verified rec by adding order by logic in findRecs
2. Refactor find upcoming rec logic
- https://github.com/lil-lab/recnet/issues/267
N/A

[recnet-api] Prioritize verified recs

---

apps/recnet/src/app/about/page.tsx

Add arxiv API Tos in about page.
Learn more: https://info.arxiv.org/help/api/index.html
- #299

[recnet-web] Add arxiv API tos

---

apps/recnet/src/components/AnnouncementCard.tsx

Fix announcement card layout
- #300

[recnet-web] Fix/announcement card UI

---

apps/recnet/src/app/onboard/page.tsx

Add invite code req form to onboard page
- #316

[recnet-web] Add invite code req form to onboard page

---

apps/recnet/src/components/RecCard.tsx

Mark verified article.
- #268 
Should see "verified" in rec card (Need to change some articles' `isVerified` to true in order to test)

[recnet-web] Add verified badge

---

apps/recnet/src/app/rec/[id]/RecReactionsList.tsx

Currently, there's a few milliseconds delay from clicking the reactions to the count of the reaction actually changes. This is because of the API latency time. Although the latency is fine for most of API, for this kind of user interaction, the latency is actually perceivable. 
There's a frontend data mutation technique called optimistic update. In short, we update the UI immediately after the data mutation is sent to backend (it assumes the outcome is successful first, and update accordingly). If the mutation sent to backend fails, UI rolls back. If it succeed as we expect, do nothing or invalid the query data (refetch).
This technique is usually used at reaction button in social media (for example, "like" button in Instagram).
lern more: 
- …

[recnet-web] Add optimistic update to reactions

---

apps/recnet-api/src/modules/email/templates/WeeklyDigest.tsx

Move invite code indicator in email template
- #341

[recnet-api] Adjust email layout: invite code

---

apps/recnet/src/components/setting/UserSettingDialog.tsx

Fix bug when login after #352 
https://recnet-git-fix-login-bug-recnet-542617e7.vercel.app/
This is the preview site for this branch (with the fix). Should be able to login without seeing any error.

[recnet-web] fix login bug
