lil-lab/recnet

src/app/search/page.tsx, src/components/UserCard.tsx
Fix issue #142.
- #142 
Fixed the issue by:
1. Adjusting the width of the page.
2. Truncate the text if the institution name is really long. 
We will try our best to adjust the width of `/search` page to fit the institution name. 
But, sorry we must truncate if that's really long in `/search` page. Since we don't set the limit of characters to the institution name, no matter how hard we adjust the width of the page (or the card), the edge case will still happen.
Preview link: https://rec-net-git-fix-long-institution-name-recnet-542617e7.vercel.app/
=> feat: truncate long institution name

apps/recnet-api/.env.sample, apps/recnet-api/README.md, apps/recnet-api/scripts/dbMigrate.sh
1. Create README.md for recnet-api.
2. Fix bug in dbMigrate script
N/A
N/A
N/A
=> [recnet-api] Create README.md

apps/recnet-api/src/app.module.ts, apps/recnet-api/src/config/common.config.ts, apps/recnet-api/src/config/env.schema.ts, apps/recnet-api/src/database/prisma/prisma.connection.provider.ts, package.json, pnpm-lock.yaml
Add config service.
1. Utilized `@nestjs/config` to manage complex configuration
2. Use `zod` to validate the whole process.env schema.
Ref:
https://docs.nestjs.com/techniques/configuration
https://github.com/lil-lab/recnet/pull/160#discussion_r1518187729
N/A
N/A
=> [recnet-api] Add config service

.vscode/settings.json, apps/recnet/src/server/routers/rec.ts
Fix get Upcoming Rec bug. Add cutoff validation step to the query logic to prevent getting rec not in this cycle.
https://cornellnlp.slack.com/archives/C061LJ5BT3J/p1711212205295569
=> Fix get Upcoming Rec bug

libs/recnet-api-model/src/lib/api/admin.ts, libs/recnet-api-model/src/lib/api/rec.ts, libs/recnet-api-model/src/lib/api/user.ts
Since params are just strings initially, if we did not add `coerce` to the schema, it will cause `recnet-api` throw error when parsing params.
Please merge this fix to the API branches you are working on right now after merge into `master`.
=> Fix: coerce api params

apps/recnet-api/src/config/env.schema.ts, apps/recnet-api/src/modules/user/entities/user.preview.entity.ts, apps/recnet-api/src/utils/middlewares/logger.middleware.ts, apps/recnet-api/src/utils/pipes/zod.validation.pipe.ts, apps/recnet-api/tsconfig.app.json, package.json, pnpm-lock.yaml
Add `strictNullChecks` to help typescript correctly inferring type from Dto.
If I did not add this, even we mark some field as optional or nullable in DTO files, typescript won't know and will seem it as non-nullable or non-undefined.
After setting this, I found some type issues (ex: `UserPreview` did not define correctly in `user.preview.entity`) and solved them in this PR.
=> [recnet-api] Add nullcheck to correct type infering from DTO

apps/recnet-api/src/utils/getJWTPayloadFromReq.ts, apps/recnet-api/src/utils/guards/auth.guard.ts, apps/recnet-api/src/utils/guards/token.type.ts, package.json, pnpm-lock.yaml
Add authorization guard
Usage:
Add `@UseGuards(AuthGuard("FirebaseJWT"))` or `@UseGuards(AuthGuard("RecnetJWT"))` before the endpoint which needs authorization and depends on which kind of JWT is expected.
And use `utils` function to extract decoded payload (only for `RecnetJWT`).
1. Remember to add `Bearer token` when using postman 
2. Ref: 
- https://stackoverflow.com/questions/62046413/is-it-possible-to-pass-a-parameter-to-a-nestjs-guard
- https://docs.nestjs.com/guards#setting-roles-per-handler
- https://docs.nestjs.com/security/authentication#implementing-the-authentication-guard
- https://stackoverflow.com/questions/58714466/in-nestjs-is-there-any-way-to-pass-data-from-guards-to-the-controller
=> Add authorization guard

apps/recnet-api/src/app.module.ts, apps/recnet-api/src/database/repository/db.repository.module.ts, apps/recnet-api/src/database/repository/invite-code.repository.ts, apps/recnet-api/src/database/repository/invite-code.repository.type.ts, apps/recnet-api/src/database/repository/rec.repository.ts, apps/recnet-api/src/modules/invite-code/dto/create.invite-code.dto.ts, apps/recnet-api/src/modules/invite-code/dto/query.invite-code.dto.ts, apps/recnet-api/src/modules/invite-code/entities/invite-code.entity.ts, apps/recnet-api/src/modules/invite-code/invite-code.controller.ts, apps/recnet-api/src/modules/invite-code/invite-code.module.ts, apps/recnet-api/src/modules/invite-code/invite-code.response.ts, apps/recnet-api/src/modules/invite-code/invite-code.service.ts, apps/recnet-api/src/modules/stat/stat.controller.ts, apps/recnet-api/src/modules/stat/stat.module.ts, apps/recnet-api/src/modules/stat/stat.response.ts, apps/recnet-api/src/modules/stat/stat.service.ts, apps/recnet-api/src/utils/auth/auth.decorator.ts, apps/recnet-api/src/utils/auth/auth.guard.ts, apps/recnet-api/src/utils/auth/auth.type.ts, apps/recnet-api/src/utils/auth/auth.user.decorator.ts, apps/recnet-api/src/utils/auth/role.guard.ts, libs/recnet-api-model/src/lib/api/admin.ts
- Invite Code API
- Stats API (used in admin panel, e.g. get user count, rec count, ...)
- Extend `Auth` decorator. 
Now we can passed in allowed roles (`UserRole[]`) in `Auth` decorator like this. If not specified any role, the decorator won't check the role of the user.
=> [recnet-api] Finish Invite Code APIs and Stats API

apps/recnet-api/src/modules/email/email.const.ts, apps/recnet-api/src/modules/email/email.controller.ts, apps/recnet-api/src/modules/email/email.service.ts
Change the cron to utc timezone
https://github.com/lil-lab/recnet/pull/204
https://github.com/lil-lab/recnet/issues/171
Will change the `WEEKLY_DIGEST_CRON` to `59 59 23 * * 2` if this works on dev.
=> [recnet-api] Change the cron to utc timezone

apps/recnet-api/package.json, apps/recnet-api/src/modules/email/email.const.ts, apps/recnet-api/src/modules/email/transporters/email.transporters.ts
Set back weekly digest cron schedule and remove resend list
N/A
=> [recnet-api][v1.2.5] Set back weekly digest cron schedule and remove resend list

apps/recnet-api/src/modules/email/email.const.ts, apps/recnet-api/src/modules/email/email.service.ts, apps/recnet-api/src/modules/email/transporters/email.dev.transporters.ts, apps/recnet-api/src/modules/email/transporters/email.transporters.ts, apps/recnet-api/src/utils/index.ts
Add email retry and set the retry limit to 3.
- https://github.com/lil-lab/recnet/issues/223
N/A
=> [recnet-api] Add email retry

libs/recnet-api-model/src/index.ts, libs/recnet-api-model/src/lib/api/article.ts, libs/recnet-api-model/src/lib/api/invite-code.ts, libs/recnet-api-model/src/lib/api/rec.ts, libs/recnet-api-model/src/lib/api/stat.ts
Reorganize api model interfaces by features. Previously, there's a `admin.ts` file inside `recnet-api-model`, however, it's unclear what's inside this file. It's better to separate api interfaces by features strictly.
Note that, although reorganizing these api model files to dedicated files, apps like `recnet` and `recnet-api` don't need to change import path since the interfaces are all barral exported from `libs/recnet-api-model/src/index.ts`.
=> [recnet-api-model] Reorganize api model by features

apps/recnet/CHANGELOG.md, apps/recnet/package.json, apps/recnet/src/app/MobileNavigator.tsx
Hide Invite code popover on mobile when unauthenticated. Currently, when logged out, the invite code popover's trigger is still there on navigation bar.
=> [recnet-web] fix: hide invite code popover when not logged in

apps/recnet-api/src/database/repository/user.repository.type.ts, apps/recnet-api/src/modules/announcement/announcement.service.ts, apps/recnet-api/src/modules/email/email.service.ts, apps/recnet-api/src/modules/invite-code/invite-code.service.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet-api/src/modules/user/entities/user.entity.ts, apps/recnet-api/src/modules/user/entities/user.preview.entity.ts, apps/recnet-api/src/modules/user/user.service.ts, apps/recnet-api/src/modules/user/user.transformer.ts, libs/recnet-api-model/src/lib/api/user.ts, libs/recnet-api-model/src/lib/model.ts
- Add `url` and `numRecs` to userPreview.
- Refactor: Extract userPreview transformer
- https://github.com/lil-lab/recnet/issues/99
- https://github.com/lil-lab/recnet/issues/129
=> [recnet-api] Add url and recommendation numbers to user preview

apps/recnet/CHANGELOG.md, apps/recnet/package.json, apps/recnet/src/app/page.tsx
Adjust size of intro video at landing page
- #265
=> [recnet-web][v1.10.1] Resize intro video

apps/recnet-api/prisma/migrations/20240905002749_add_is_activated_to_user/down.sql, apps/recnet-api/prisma/migrations/20240905002749_add_is_activated_to_user/migration.sql, apps/recnet-api/prisma/schema.prisma, apps/recnet-api/src/database/repository/user.repository.ts, apps/recnet-api/src/database/repository/user.repository.type.ts, apps/recnet-api/src/modules/announcement/announcement.controller.ts, apps/recnet-api/src/modules/invite-code/invite-code.controller.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet-api/src/modules/stat/stat.controller.ts, apps/recnet-api/src/modules/user/dto/update.user.dto.ts, apps/recnet-api/src/modules/user/entities/user.entity.ts, apps/recnet-api/src/modules/user/user.controller.ts, apps/recnet-api/src/modules/user/user.service.ts, apps/recnet-api/src/utils/auth/activated.guard.ts, apps/recnet-api/src/utils/auth/auth.decorator.ts, apps/recnet-api/src/utils/error/recnet.error.const.ts, libs/recnet-api-model/src/lib/api/user.ts, libs/recnet-api-model/src/lib/model.ts
Tech design doc: [notion](https://www.notion.so/Deactivate-Account-6f43ae29772442e293d8f0d9641d2be1)
1. Add `isActivated` to the db user table
2. Exclude the following and followedBy users and user queries that are non-activated by Prisma where
3. Add ActivatedGuard in Auth decorator to prevent non-activated users access the APIs
4. Add PATCH /users/me/activate to reactivate/deactivate the account
5. Add validation in follow/unfollow/getRecs API to see if the target user is activated
- https://github.com/lil-lab/recnet/issues/90
How to test manually?
1. Hit `PATCH /users/me/activate` to deactivate your account.
2. Try accessing other APIs such as recs, invite-codes. You should get an error.
3. Try to use another account to follow and unfollow the deactivated user. You should get an error. …
=> [recnet-api] Deactivate account

apps/recnet/src/app/MobileNavigator.tsx, apps/recnet/src/app/feeds/LeftPanel.tsx, apps/recnet/src/components/rec/NewArticleForm.tsx, apps/recnet/src/components/rec/RecEditForm.tsx
Rename two confusing components and give a better semantic name to avoid confusion in the future.
A two-step flow to recommend a new article. Two use cases:
1. User doesn't have an upcoming rec in this cycle yet.
2. User already made a rec, but want to rec another article
A simple form for user who already made a rec in this cycle to edit the description (tl;dr field).
There's a button like `Rec another form?` and it will redirect user to `NewArticleForm` 
N/A
Manual test: 
- Everything should behave the same.
=> [recnet-web] Rename recform components

apps/recnet-api/prisma/migrations/20240907214307_add_self_rec_flag_into_rec_model/down.sql, apps/recnet-api/prisma/migrations/20240907214307_add_self_rec_flag_into_rec_model/migration.sql, apps/recnet-api/prisma/schema.prisma, apps/recnet-api/src/database/repository/rec.repository.ts, apps/recnet-api/src/modules/rec/dto/create.rec.dto.ts, apps/recnet-api/src/modules/rec/dto/update.rec.dto.ts, apps/recnet-api/src/modules/rec/rec.controller.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet/src/components/rec/RecArticleForm.tsx, apps/recnet/src/components/rec/RecForm.tsx, apps/recnet/src/server/routers/rec.ts, libs/recnet-api-model/src/lib/api/rec.ts
We need a “self-rec” flag to display at feeds and email digest. 
This PR updated prisma schema and update APIs to enable marking rec as "self-rec".
Design docs: https://www.notion.so/Self-review-feature-4fcb73e72d0d41abbb4dafef0c672512?pvs=4
- #269 
- Open recnet web app and try to create rec/edit rec.
- All bahaviors should remain the same.
- Try to use Postman to turn a rec to “self-rec” rec
- Verify the API is working properly via inspecting db (open prisma studio)
- Try to use Postman to create a “self-rec” rec
- Verify the API is working properly via inspecting db (open prisma studio)
=> [recnet-api] Self-rec flag 

apps/recnet-api/buildspec.yml
Nx will fail the whole pipeline if nx cloud is not activated. We need to disable this feature.
Learn more: https://github.com/nrwl/nx/issues/22444
Solutions: https://github.com/nrwl/nx/issues/22444#issuecomment-2016671263
=> [recnet-api] Disable nx cloud

apps/recnet-api/src/database/repository/rec.repository.type.ts, apps/recnet-api/src/modules/rec/entities/rec.entity.ts, libs/recnet-api-model/src/lib/model.ts
Add `isSelfRec` property to rec api model.
- #269 
Try to hit `POST /recs/upcoming`, `PATCH /recs/upcoming`, or `GET /recs/upcoming` in postman, the response data should contain `isSelfRec` field.
=> [recnet-api] Add self rec in rec

apps/recnet/CHANGELOG.md, apps/recnet/package.json, apps/recnet/src/components/RecCard.tsx, apps/recnet/src/components/rec/NewArticleForm.tsx, apps/recnet/src/components/rec/RecEditForm.tsx
- Add "self-rec" checkbox in rec forms (`NewArticleForm`/`RecEditForm`). 
- Add "self-rec" badge in `RecCard`.
- Add "self-rec" badge in email digest's `RecCard`.
Email digest:
- #271 
- #270 
- #272 
- Try create a "self-rec" using rec form
- Try to toggle the "isSelfRec" option while editing the rec
=> [recnet-web][v1.11.0] Self rec checkbox in rec forms

apps/recnet-api/src/modules/user/user.controller.ts
Allow deactivated user use `GET /users/me` to get user data.
- Turn a user to deactivated (either by overwrite using prisma studio or via API)
- Try to use `GET /users/me`
- Should get user data
=> [recnet-api] Allow deactivated user get user info

apps/recnet-api/package.json, apps/recnet-api/src/modules/user/user.controller.ts
- #288 
- Turn a user to deactivated (via API)
- Try to use `GET /users/me`
- Should get user data
=> [recnet-api][v.1.4.2] Allow deactivated user get user info

apps/recnet/CHANGELOG.md, apps/recnet/package.json, apps/recnet/src/app/AuthContext.ts, apps/recnet/src/app/[handle]/Profile.tsx, apps/recnet/src/app/[handle]/UserSettingDialog.tsx, apps/recnet/src/app/[handle]/page.tsx, apps/recnet/src/app/reactivate/ReactivateButton.tsx, apps/recnet/src/app/reactivate/page.tsx, apps/recnet/src/components/FollowButton.tsx, apps/recnet/src/components/hoc/withAuthRequired.tsx, apps/recnet/src/server/routers/user.ts
Design docs: https://www.notion.so/Deactivate-Account-6f43ae29772442e293d8f0d9641d2be1?pvs=4
- Extend `EditProfileDialog` to `UserSettingDialog`
- Add deactivate button to `UserSettingDialog`
- Add `/reactivate` page (deactivated user will be directed to this page after logging in)
- #90 
New component: `UserSettingDialog` (extend from prev `EditProfileDialog`)
`/reactivate` page
Try to deactivate and reactivate. When deactivated, actions like follow someone should be disallowed. And user should not appear in search result.
=> [recnet-web][v.1.12.0] Deactivate account feature

apps/recnet/src/app/[handle]/HistoricalRecs.tsx, apps/recnet/src/app/all-users/page.tsx, apps/recnet/src/app/feeds/page.tsx, apps/recnet/src/app/onboard/OnboardingDialog.tsx, apps/recnet/src/app/onboard/page.tsx, apps/recnet/src/app/page.tsx, apps/recnet/src/app/search/page.tsx, apps/recnet/src/components/UserCard.tsx, apps/recnet/src/utils/getDataFromInfiniteQuery.spec.ts, apps/recnet/src/utils/getDataFromInfiniteQuery.ts
Add new onboarding flow. After new user fill all required information, there will be a dialog showing up to ask user to follow other uses. This dialog can be extend to multi-step onboarding guide in the future. Currently, just one step.
- #83 
Also extract the replicated logic about transforming infinite query data by new utils function `getDataFromInfiniteQuery`.
Try to log in using a new account.
- Should see the onboarding dialog like this after finishing the registration form.
=> [recnet-web][v.1.13.0] Add new onboarding step

apps/recnet-api/src/database/repository/rec.repository.ts, apps/recnet-api/src/modules/rec/rec.controller.ts, apps/recnet-api/src/modules/rec/rec.response.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet-api/src/utils/error/recnet.error.const.ts, apps/recnet-api/src/utils/filters/recnet.exception.filter.ts, libs/recnet-api-model/src/lib/api/rec.ts
Add new API endpoint `GET /recs/rec/:id`
- #258
=> [recnet-api] Add new api endpoint: get single rec by id

apps/recnet-api/package.json, apps/recnet-api/src/database/repository/rec.repository.ts, apps/recnet-api/src/modules/rec/rec.controller.ts, apps/recnet-api/src/modules/rec/rec.response.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet-api/src/utils/error/recnet.error.const.ts, apps/recnet-api/src/utils/filters/recnet.exception.filter.ts, apps/recnet/CHANGELOG.md, apps/recnet/package.json, apps/recnet/src/app/[handle]/HistoricalRecs.tsx, apps/recnet/src/app/all-users/page.tsx, apps/recnet/src/app/feeds/page.tsx, apps/recnet/src/app/onboard/OnboardingDialog.tsx, apps/recnet/src/app/onboard/page.tsx, apps/recnet/src/app/page.tsx, apps/recnet/src/app/search/page.tsx, apps/recnet/src/components/UserCard.tsx, apps/recnet/src/utils/getDataFromInfiniteQuery.spec.ts, apps/recnet/src/utils/getDataFromInfiniteQuery.ts, libs/recnet-api-model/src/lib/api/rec.ts
=> release recnet-web v.1.13.0/recnet-api v1.5.0

apps/recnet/src/components/rec/NewArticleForm.tsx
When creating new rec, if article is returned by our API (found by arxiv API), we use the "unified link" instead of the original link provided by user. Thus, if user provide a pdf arxiv link, we will overwrite by a arxiv abs link.
- #298 
Try to use the any arxiv pdf link when creating new rec, you should see it's replaced by an abs arxiv link.
=> [recnet-web] Fix: Use unified link in rec form

.github/workflows/release-action.yml, libs/recnet-release-action/action.yml, libs/recnet-release-action/out/index.js, libs/recnet-release-action/package.json, libs/recnet-release-action/src/lib/env.ts, libs/recnet-release-action/src/lib/github.spec.ts, libs/recnet-release-action/src/lib/github.ts, libs/recnet-release-action/src/lib/main.ts
Refactor release action.
Main changes
- Diff commits retrieval
- Before: use a tag to get commits from last time this action run to current commit (This seems to be buggy when PRs are not merge in order)
- Now: instead of using tag, just simply get diff commits between dev and master
- Modify Issue & PR extraction logic from commit message (capture PR and issue via regex more accurately)
- Include staging links in the end
=> [recnet-release-action] Fix/release action

apps/recnet-api/src/database/repository/digital-library.repository.ts, apps/recnet-api/src/database/repository/digital-library.repository.type.ts, apps/recnet-api/src/modules/digital-library/digital-library.admin.service.ts, apps/recnet-api/src/modules/digital-library/digital-library.controller.ts, apps/recnet-api/src/modules/digital-library/digital-library.module.ts, apps/recnet-api/src/modules/digital-library/digital-library.response.ts, apps/recnet-api/src/modules/digital-library/dto/create.digital-library.dto.ts, apps/recnet-api/src/modules/digital-library/dto/query.digital-library.dto.ts, apps/recnet-api/src/modules/digital-library/dto/update.digital-library.dto.ts, apps/recnet-api/src/modules/digital-library/entities/digital-library.entity.ts, apps/recnet-api/src/utils/error/recnet.error.const.ts, apps/recnet/src/app/reactivate/ReactivateButton.tsx, apps/recnet/src/app/reactivate/page.tsx, libs/recnet-api-model/src/index.ts, libs/recnet-api-model/src/lib/api/digital-library.ts, libs/recnet-api-model/src/lib/model.ts
Create API for admin to conduct CRUD for `Digital Library`.
Add the following APIs:
- `GET /digital-libraries`
- `POST /digital-libraries`
- `PATCH /digital-libraries/:id`
- `DELETE /digital-libraries/:id`
- `POST /digital-libraries/rank`
Design Doc: [Notion](https://www.notion.so/e5979d5d153b4df89ccd622c488dbbd3?v=ea2512f452514fad9f1331fab3923738&p=26e1673576a84541bb4d789fea2ff518&pm=s)
- https://github.com/lil-lab/recnet/issues/254
N/A
=> [recnet-api] Add digital library CRUD APIs

apps/recnet/src/app/admin/announcement/inapp/AnnouncementForm.tsx, apps/recnet/src/app/feeds/CutoffDatePicker.tsx, apps/recnet/src/app/feeds/page.tsx, apps/recnet/src/app/help/page.tsx, apps/recnet/src/components/DatePicker.tsx, libs/recnet-date-fns/src/lib/recnet-date-fns.ts
This PR mainly address two issues
1. Duplicate code in `CutoffDatePicker` and in `DatePicker`. This PR refactor the code duplication in `CutoffDatePicker` and extend `DatePicker` functionality.
2. Currently, the `/feeds` page doesn't show the current cycle. When navigating to old cycles, it's hard to know which cycle we are viewing currently.
- #253 
The CutoffDatePicker should behave the same as in the past.
- Can only select Tuesday.
We could see a "current cycle" indicator in feeds page like this
=> [recnet-web] Display cycle in feeds page & consolidate date picker component

apps/recnet/src/app/rec/[id]/opengraph-image.tsx
Add desc and self-rec badge to og
- #324 
- #317 
Go to `localhost:3000/rec/{id}/opengraph-image`, you should see rec desc included. (and self-rec badge if that rec is self-rec by someone)
=> [recnet-web] Add desc and self-rec badge to og

apps/recnet-api/src/database/repository/rec.repository.type.ts, apps/recnet-api/src/modules/email/email.service.ts, apps/recnet-api/src/modules/rec/entities/rec.entity.ts, apps/recnet-api/src/modules/rec/rec.controller.ts, apps/recnet-api/src/modules/rec/rec.service.ts, apps/recnet-api/src/modules/rec/rec.transformer.ts, apps/recnet-api/src/utils/auth/auth.decorator.ts, apps/recnet-api/src/utils/auth/auth.guard.ts, apps/recnet-api/src/utils/auth/auth.type.ts, apps/recnet-api/src/utils/auth/auth.user.decorator.ts, libs/recnet-api-model/src/lib/model.ts
Add rec reaction to rec related API.
Design Doc: [Notion](https://www.notion.so/Rec-Emoji-Reaction-ad4c0db048574a6183a672b25d209e5c)
- GET /recs/rec/{id}
- GET /recs
- GET /recs/feed
The Rec schema in response API becomes:
```
{
"id": "string",
"description": "string",
...
"reaction": {
"selfReactions": ["string"],  // list emun of reaction that user clicked
"numReactions": [
{
"type": "string",  // enum of reaction
"count": "number" // total count of the reaction
}
]
}
}
```
- https://github.com/lil-lab/recnet/issues/60
As `GET /recs/rec/{id}` and `GET /recs/` do not require an Auth user to login, I added a decorator of `@AuthOptional` to get the user information from jwt token.
1. Hit `POST /recs/{id}/reactions` and `DELETE /recs/{id}/reactions` to create and delete rec for a specific …
=> [recnet-api] add rec reaction to get rec api

.github/workflows/release-action.yml, libs/recnet-release-action/action.yml, libs/recnet-release-action/scripts/hash_source.sh
Cache the output of `nx build recnet-release-action` using the hash of source code in `libs/recnet-release-action/src` to accelerate gh action
Successful run 1 (cache miss): https://github.com/lil-lab/recnet/actions/runs/11335345342/attempts/1
Successful run 2 (cache hit): https://github.com/lil-lab/recnet/actions/runs/11335345342
You can see in the first run, cache doesn't hit, and the action start downloading node packages and compiling the typescript files.
And it saves the output in cache in the end of first successful run.
In the second run, you can see it did hit the cache and skip the downloading and compiiing steps
=> [recnet-release-action] cache gh action build output

apps/recnet/src/app/rec/[id]/RecPageContent.tsx, apps/recnet/src/app/rec/[id]/RecReactionsList.tsx, apps/recnet/src/components/RecCard.tsx, apps/recnet/src/server/routers/middleware.ts, apps/recnet/src/server/routers/rec.ts
Add reactions buttons under rec page
- #60 
Find a rec and go to rec page `rec/:id`
- When not logged in, should be able to view reactions. But when clicking emojis, should see an error toast shows up.
- When logged in, should be able to select reaction. And after selection, should see the reaction chip, which displays how many users have clicked that reaction, displays the number correctly.
- When click again (no matter using the reaction popover or click on reaction chip), should remove that reaction (reaction count decrement by 1)
Reaction popover:
Reaction chip:
=> [recnet-web] Rec reactions UI

apps/recnet/src/app/feeds/page.tsx
Should prioritize verified rec but it didn't right now.
Remove the old shuffle logic (this causes the bug)
Should see verified rec always prioritize
=> [recnet-web] fix bug - not priortize verified rec

apps/recnet-api/prisma/migrations/20241021180415_add_article_abstract/down.sql, apps/recnet-api/prisma/migrations/20241021180415_add_article_abstract/migration.sql, apps/recnet-api/prisma/schema.prisma, apps/recnet-api/src/database/repository/article.repository.type.ts, apps/recnet-api/src/modules/article/article.controller.ts, apps/recnet-api/src/modules/article/article.response.ts, apps/recnet-api/src/modules/article/entities/article.entity.ts, apps/recnet-api/src/modules/digital-library/arxiv.service.ts, apps/recnet-api/src/modules/digital-library/digital-library.type.ts, apps/recnet-api/src/modules/digital-library/specs/arxiv.service.spec.ts, apps/recnet-api/src/modules/rec/dto/create.rec.dto.ts, apps/recnet-api/src/modules/rec/dto/update.rec.dto.ts, apps/recnet/src/components/rec/NewArticleForm.tsx, libs/recnet-api-model/src/lib/api/rec.ts, libs/recnet-api-model/src/lib/model.ts
Get the paper abstract from arXiv.
- https://github.com/lil-lab/recnet/issues/334
Use `GET /article?link={arXiv URL}` to test this feature. The response should contain the abstract of the article.
=> [recnet-api] Get abstract from arXiv

apps/recnet/src/app/rec/[id]/RecReactionsList.tsx
In optimistic UI, we always assume the mutation API will be successfully and predict the next state of UI and render it first before we get the API response. 
In our case, for clicking a new reaction, I forget to cover one case, that is, the current user is the first one clicking that reaction. 
This PR added this case to improve UX.
- #60 
You should feel the UI updating "immediately" after you clicked a reaction (even if you are the first one who click that reaction).
=> [recnet-web] Cover uncovered case in reaction optimistic UI

apps/recnet/src/app/[handle]/opengraph-image.tsx, apps/recnet/src/app/opengraph-image.tsx, apps/recnet/src/app/rec/[id]/opengraph-image.tsx, apps/recnet/src/app/rec/[id]/page.tsx
- Increase OG image size
- Fix rec page metadata desc
- #342 
- OG image size should be bigger (This is a little bit hard to test, sometimes it works in slack, sometimes it doesn't. I am guessing maybe it's related to slack's cache. But even if I cleared cache, still unstable. Anyway, I can confirm it's def bigger by inspecting in html <head>. The size is correct in below image)
- Rec page's desc should be "{username} recommends: ${desc}"
=> [recnet-web] Adjust og and metadata desc

apps/recnet-api/src/database/repository/user.repository.ts, apps/recnet-api/src/database/repository/user.repository.type.ts, apps/recnet-api/src/modules/user/entities/user.subscription.entity.ts, apps/recnet-api/src/modules/user/user.controller.ts, apps/recnet-api/src/modules/user/user.response.ts, apps/recnet-api/src/modules/user/user.service.ts, apps/recnet-api/src/utils/error/recnet.error.const.ts, libs/recnet-api-model/src/lib/api/user.ts, libs/recnet-api-model/src/lib/model.ts
Add user subscriptions api
- `GET /users/subscriptions`
- `POST /users/subscriptions`
- https://github.com/lil-lab/recnet/issues/260
Design doc: https://www.notion.so/Multiple-Distributing-Channels-Slack-Integration-61323d4345c547cb869129e117c5d722
1. Run server locally
2. Hit the two new apis with your Auth token
=> [recnet-api] Add user subscriptions api

apps/recnet/src/app/rec/[id]/opengraph-image.tsx
Redesign rec page og style
- #355 
Before:
It looks like this now
=> [recnet-web] Update rec page og design

apps/recnet-api/src/database/repository/user.repository.ts
Follow the person who invites the user when creating an account
- https://github.com/lil-lab/recnet/issues/356
N/A
1. Run local server
2. Create a user by hitting `POST /users/me`
3. Check if there is a following record that followerId = userId and followingId = inviterId
TBA
=> [recnet-api] Follow the person who invites the user

libs/recnet-release-action/src/lib/github.spec.ts, libs/recnet-release-action/src/lib/github.ts
Each time this action run, it will request reviews from committers. However, if the committers already approved, the request review operation will overwrite the approved review from committers. This PR fix this issue by checking the current review status before requesting review.
=> [release-action] Fix bug: request status being overwritten

apps/recnet-api/src/modules/slack/templates/weekly-digest.template.ts
There's a "false" prefix in slack template. Remove it.
=> [recnet-api] Fix slack message bug

apps/recnet-api/src/modules/slack/slack.service.ts, apps/recnet-api/src/modules/user/dto/slack-oauth.user.dto.ts, apps/recnet-api/src/modules/user/user.controller.ts, apps/recnet-api/src/modules/user/user.service.ts, apps/recnet/src/app/api/slack/oauth/callback/route.ts, apps/recnet/src/server/routers/subscription.ts, libs/recnet-api-model/src/lib/api/user.ts
Fix the issue of `bad_redirect_uri` in staging env. The root cause is that if we specify the redirect_uri in the authorize and redirect stage, we should also pass the redirect_uri with code to access information in our backend service. Otherwise, if we setup multiple redirect URLs for the app, it will always take the first redirect URL and oauth will fail.
Ref: https://api.slack.com/authentication/oauth-v2#asking
N/A
=> fix: send redirect uri to slac Oauth access API

apps/recnet-api/src/modules/email/email.service.ts, apps/recnet-api/src/modules/subscription/subscription.controller.ts
- The "From" field now is `lil.recnet@gmail.com` and we want it to be `RecNet`
- Misc: add back email test api `POST /subscriptions/email/test`
- #247 
use `POST /subscriptions/email/test`
Comparison
=> [recnet-api] Fix: change from field of email

apps/recnet-api/src/modules/slack/templates/weekly-digest.template.ts
Remove excessive links in slack weekly digest template
#374 
Before:
Now:
=> [recnet-api] Remove excessive links in slack weekly digest template
